#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ_test
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BoomDB")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttimezones_t(timezones_t instance);
    partial void Updatetimezones_t(timezones_t instance);
    partial void Deletetimezones_t(timezones_t instance);
    partial void Insertdays_sessions_t(days_sessions_t instance);
    partial void Updatedays_sessions_t(days_sessions_t instance);
    partial void Deletedays_sessions_t(days_sessions_t instance);
    partial void Insertglobal_session_t(global_session_t instance);
    partial void Updateglobal_session_t(global_session_t instance);
    partial void Deleteglobal_session_t(global_session_t instance);
    partial void Insertpersonal_info_t(personal_info_t instance);
    partial void Updatepersonal_info_t(personal_info_t instance);
    partial void Deletepersonal_info_t(personal_info_t instance);
    partial void Insertplaystation_timezone(playstation_timezone instance);
    partial void Updateplaystation_timezone(playstation_timezone instance);
    partial void Deleteplaystation_timezone(playstation_timezone instance);
    partial void Inserttables_t(tables_t instance);
    partial void Updatetables_t(tables_t instance);
    partial void Deletetables_t(tables_t instance);
    partial void Insertclient_info_t(client_info_t instance);
    partial void Updateclient_info_t(client_info_t instance);
    partial void Deleteclient_info_t(client_info_t instance);
    #endregion
		
		public dbDataContext() : 
				base(global::LINQ_test.Properties.Settings.Default.BoomDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<account_savings_t> account_savings_ts
		{
			get
			{
				return this.GetTable<account_savings_t>();
			}
		}
		
		public System.Data.Linq.Table<timezones_t> timezones_ts
		{
			get
			{
				return this.GetTable<timezones_t>();
			}
		}
		
		public System.Data.Linq.Table<days_sessions_t> days_sessions_ts
		{
			get
			{
				return this.GetTable<days_sessions_t>();
			}
		}
		
		public System.Data.Linq.Table<discounts_t> discounts_ts
		{
			get
			{
				return this.GetTable<discounts_t>();
			}
		}
		
		public System.Data.Linq.Table<global_session_t> global_session_ts
		{
			get
			{
				return this.GetTable<global_session_t>();
			}
		}
		
		public System.Data.Linq.Table<payments_t> payments_ts
		{
			get
			{
				return this.GetTable<payments_t>();
			}
		}
		
		public System.Data.Linq.Table<personal_info_t> personal_info_ts
		{
			get
			{
				return this.GetTable<personal_info_t>();
			}
		}
		
		public System.Data.Linq.Table<playstation_timezone> playstation_timezones
		{
			get
			{
				return this.GetTable<playstation_timezone>();
			}
		}
		
		public System.Data.Linq.Table<tables_t> tables_ts
		{
			get
			{
				return this.GetTable<tables_t>();
			}
		}
		
		public System.Data.Linq.Table<client_info_t> client_info_ts
		{
			get
			{
				return this.GetTable<client_info_t>();
			}
		}
		
		public System.Data.Linq.Table<session_accounting_t> session_accounting_ts
		{
			get
			{
				return this.GetTable<session_accounting_t>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.account_savings_t")]
	public partial class account_savings_t
	{
		
		private string _client_id;
		
		private double _savings;
		
		public account_savings_t()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_id", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string client_id
		{
			get
			{
				return this._client_id;
			}
			set
			{
				if ((this._client_id != value))
				{
					this._client_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_savings", DbType="Float NOT NULL")]
		public double savings
		{
			get
			{
				return this._savings;
			}
			set
			{
				if ((this._savings != value))
				{
					this._savings = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.timezones_t")]
	public partial class timezones_t : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _timezone_name;
		
		private System.TimeSpan _timezone_start;
		
		private System.TimeSpan _timezone_end;
		
		private EntitySet<playstation_timezone> _playstation_timezones;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontimezone_nameChanging(string value);
    partial void Ontimezone_nameChanged();
    partial void Ontimezone_startChanging(System.TimeSpan value);
    partial void Ontimezone_startChanged();
    partial void Ontimezone_endChanging(System.TimeSpan value);
    partial void Ontimezone_endChanged();
    #endregion
		
		public timezones_t()
		{
			this._playstation_timezones = new EntitySet<playstation_timezone>(new Action<playstation_timezone>(this.attach_playstation_timezones), new Action<playstation_timezone>(this.detach_playstation_timezones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timezone_name", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string timezone_name
		{
			get
			{
				return this._timezone_name;
			}
			set
			{
				if ((this._timezone_name != value))
				{
					this.Ontimezone_nameChanging(value);
					this.SendPropertyChanging();
					this._timezone_name = value;
					this.SendPropertyChanged("timezone_name");
					this.Ontimezone_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timezone_start", DbType="Time NOT NULL")]
		public System.TimeSpan timezone_start
		{
			get
			{
				return this._timezone_start;
			}
			set
			{
				if ((this._timezone_start != value))
				{
					this.Ontimezone_startChanging(value);
					this.SendPropertyChanging();
					this._timezone_start = value;
					this.SendPropertyChanged("timezone_start");
					this.Ontimezone_startChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timezone_end", DbType="Time NOT NULL")]
		public System.TimeSpan timezone_end
		{
			get
			{
				return this._timezone_end;
			}
			set
			{
				if ((this._timezone_end != value))
				{
					this.Ontimezone_endChanging(value);
					this.SendPropertyChanging();
					this._timezone_end = value;
					this.SendPropertyChanged("timezone_end");
					this.Ontimezone_endChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="timezones_t_playstation_timezone", Storage="_playstation_timezones", ThisKey="timezone_name", OtherKey="timezone_name")]
		public EntitySet<playstation_timezone> playstation_timezones
		{
			get
			{
				return this._playstation_timezones;
			}
			set
			{
				this._playstation_timezones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_playstation_timezones(playstation_timezone entity)
		{
			this.SendPropertyChanging();
			entity.timezones_t = this;
		}
		
		private void detach_playstation_timezones(playstation_timezone entity)
		{
			this.SendPropertyChanging();
			entity.timezones_t = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.days_sessions_t")]
	public partial class days_sessions_t : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _daily_id;
		
		private int _session_id;
		
		private int _client_num;
		
		private System.Nullable<System.TimeSpan> _start_game;
		
		private System.Nullable<System.TimeSpan> _end_game;
		
		private string _playstation_id;
		
		private string _client_id;
		
		private EntityRef<global_session_t> _global_session_t;
		
		private EntityRef<tables_t> _tables_t;
		
		private EntityRef<client_info_t> _client_info_t;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondaily_idChanging(System.Nullable<int> value);
    partial void Ondaily_idChanged();
    partial void Onsession_idChanging(int value);
    partial void Onsession_idChanged();
    partial void Onclient_numChanging(int value);
    partial void Onclient_numChanged();
    partial void Onstart_gameChanging(System.Nullable<System.TimeSpan> value);
    partial void Onstart_gameChanged();
    partial void Onend_gameChanging(System.Nullable<System.TimeSpan> value);
    partial void Onend_gameChanged();
    partial void Onplaystation_idChanging(string value);
    partial void Onplaystation_idChanged();
    partial void Onclient_idChanging(string value);
    partial void Onclient_idChanged();
    #endregion
		
		public days_sessions_t()
		{
			this._global_session_t = default(EntityRef<global_session_t>);
			this._tables_t = default(EntityRef<tables_t>);
			this._client_info_t = default(EntityRef<client_info_t>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daily_id", DbType="Int")]
		public System.Nullable<int> daily_id
		{
			get
			{
				return this._daily_id;
			}
			set
			{
				if ((this._daily_id != value))
				{
					if (this._global_session_t.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondaily_idChanging(value);
					this.SendPropertyChanging();
					this._daily_id = value;
					this.SendPropertyChanged("daily_id");
					this.Ondaily_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_session_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int session_id
		{
			get
			{
				return this._session_id;
			}
			set
			{
				if ((this._session_id != value))
				{
					this.Onsession_idChanging(value);
					this.SendPropertyChanging();
					this._session_id = value;
					this.SendPropertyChanged("session_id");
					this.Onsession_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_num", DbType="Int NOT NULL")]
		public int client_num
		{
			get
			{
				return this._client_num;
			}
			set
			{
				if ((this._client_num != value))
				{
					this.Onclient_numChanging(value);
					this.SendPropertyChanging();
					this._client_num = value;
					this.SendPropertyChanged("client_num");
					this.Onclient_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_game", DbType="Time")]
		public System.Nullable<System.TimeSpan> start_game
		{
			get
			{
				return this._start_game;
			}
			set
			{
				if ((this._start_game != value))
				{
					this.Onstart_gameChanging(value);
					this.SendPropertyChanging();
					this._start_game = value;
					this.SendPropertyChanged("start_game");
					this.Onstart_gameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_game", DbType="Time")]
		public System.Nullable<System.TimeSpan> end_game
		{
			get
			{
				return this._end_game;
			}
			set
			{
				if ((this._end_game != value))
				{
					this.Onend_gameChanging(value);
					this.SendPropertyChanging();
					this._end_game = value;
					this.SendPropertyChanged("end_game");
					this.Onend_gameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_playstation_id", DbType="VarChar(10)")]
		public string playstation_id
		{
			get
			{
				return this._playstation_id;
			}
			set
			{
				if ((this._playstation_id != value))
				{
					if (this._tables_t.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onplaystation_idChanging(value);
					this.SendPropertyChanging();
					this._playstation_id = value;
					this.SendPropertyChanged("playstation_id");
					this.Onplaystation_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_id", DbType="VarChar(10)")]
		public string client_id
		{
			get
			{
				return this._client_id;
			}
			set
			{
				if ((this._client_id != value))
				{
					if (this._client_info_t.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onclient_idChanging(value);
					this.SendPropertyChanging();
					this._client_id = value;
					this.SendPropertyChanged("client_id");
					this.Onclient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="global_session_t_days_sessions_t", Storage="_global_session_t", ThisKey="daily_id", OtherKey="daily_id", IsForeignKey=true)]
		public global_session_t global_session_t
		{
			get
			{
				return this._global_session_t.Entity;
			}
			set
			{
				global_session_t previousValue = this._global_session_t.Entity;
				if (((previousValue != value) 
							|| (this._global_session_t.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._global_session_t.Entity = null;
						previousValue.days_sessions_ts.Remove(this);
					}
					this._global_session_t.Entity = value;
					if ((value != null))
					{
						value.days_sessions_ts.Add(this);
						this._daily_id = value.daily_id;
					}
					else
					{
						this._daily_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("global_session_t");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tables_t_days_sessions_t", Storage="_tables_t", ThisKey="playstation_id", OtherKey="playstation_id", IsForeignKey=true)]
		public tables_t tables_t
		{
			get
			{
				return this._tables_t.Entity;
			}
			set
			{
				tables_t previousValue = this._tables_t.Entity;
				if (((previousValue != value) 
							|| (this._tables_t.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tables_t.Entity = null;
						previousValue.days_sessions_ts.Remove(this);
					}
					this._tables_t.Entity = value;
					if ((value != null))
					{
						value.days_sessions_ts.Add(this);
						this._playstation_id = value.playstation_id;
					}
					else
					{
						this._playstation_id = default(string);
					}
					this.SendPropertyChanged("tables_t");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="client_info_t_days_sessions_t", Storage="_client_info_t", ThisKey="client_id", OtherKey="client_id", IsForeignKey=true)]
		public client_info_t client_info_t
		{
			get
			{
				return this._client_info_t.Entity;
			}
			set
			{
				client_info_t previousValue = this._client_info_t.Entity;
				if (((previousValue != value) 
							|| (this._client_info_t.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._client_info_t.Entity = null;
						previousValue.days_sessions_ts.Remove(this);
					}
					this._client_info_t.Entity = value;
					if ((value != null))
					{
						value.days_sessions_ts.Add(this);
						this._client_id = value.client_id;
					}
					else
					{
						this._client_id = default(string);
					}
					this.SendPropertyChanged("client_info_t");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.discounts_t")]
	public partial class discounts_t
	{
		
		private System.DateTime _startDate;
		
		private System.DateTime _endDate;
		
		private double _discountSize;
		
		private string _discount_reason;
		
		private string _discount_timezones;
		
		private string _discount_playstation_ids;
		
		public discounts_t()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startDate", DbType="DateTime NOT NULL")]
		public System.DateTime startDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				if ((this._startDate != value))
				{
					this._startDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endDate", DbType="DateTime NOT NULL")]
		public System.DateTime endDate
		{
			get
			{
				return this._endDate;
			}
			set
			{
				if ((this._endDate != value))
				{
					this._endDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discountSize", DbType="Float NOT NULL")]
		public double discountSize
		{
			get
			{
				return this._discountSize;
			}
			set
			{
				if ((this._discountSize != value))
				{
					this._discountSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_reason", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string discount_reason
		{
			get
			{
				return this._discount_reason;
			}
			set
			{
				if ((this._discount_reason != value))
				{
					this._discount_reason = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_timezones", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string discount_timezones
		{
			get
			{
				return this._discount_timezones;
			}
			set
			{
				if ((this._discount_timezones != value))
				{
					this._discount_timezones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_playstation_ids", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string discount_playstation_ids
		{
			get
			{
				return this._discount_playstation_ids;
			}
			set
			{
				if ((this._discount_playstation_ids != value))
				{
					this._discount_playstation_ids = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.global_session_t")]
	public partial class global_session_t : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _daily_id;
		
		private System.DateTime _start_session;
		
		private System.DateTime _end_session;
		
		private string _operator_id;
		
		private string _administrator_id;
		
		private EntitySet<days_sessions_t> _days_sessions_ts;
		
		private EntityRef<personal_info_t> _personal_info_t;
		
		private EntityRef<personal_info_t> _personal_info_t1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondaily_idChanging(int value);
    partial void Ondaily_idChanged();
    partial void Onstart_sessionChanging(System.DateTime value);
    partial void Onstart_sessionChanged();
    partial void Onend_sessionChanging(System.DateTime value);
    partial void Onend_sessionChanged();
    partial void Onoperator_idChanging(string value);
    partial void Onoperator_idChanged();
    partial void Onadministrator_idChanging(string value);
    partial void Onadministrator_idChanged();
    #endregion
		
		public global_session_t()
		{
			this._days_sessions_ts = new EntitySet<days_sessions_t>(new Action<days_sessions_t>(this.attach_days_sessions_ts), new Action<days_sessions_t>(this.detach_days_sessions_ts));
			this._personal_info_t = default(EntityRef<personal_info_t>);
			this._personal_info_t1 = default(EntityRef<personal_info_t>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daily_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int daily_id
		{
			get
			{
				return this._daily_id;
			}
			set
			{
				if ((this._daily_id != value))
				{
					this.Ondaily_idChanging(value);
					this.SendPropertyChanging();
					this._daily_id = value;
					this.SendPropertyChanged("daily_id");
					this.Ondaily_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_session", DbType="DateTime NOT NULL")]
		public System.DateTime start_session
		{
			get
			{
				return this._start_session;
			}
			set
			{
				if ((this._start_session != value))
				{
					this.Onstart_sessionChanging(value);
					this.SendPropertyChanging();
					this._start_session = value;
					this.SendPropertyChanged("start_session");
					this.Onstart_sessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_session", DbType="DateTime NOT NULL")]
		public System.DateTime end_session
		{
			get
			{
				return this._end_session;
			}
			set
			{
				if ((this._end_session != value))
				{
					this.Onend_sessionChanging(value);
					this.SendPropertyChanging();
					this._end_session = value;
					this.SendPropertyChanged("end_session");
					this.Onend_sessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operator_id", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string operator_id
		{
			get
			{
				return this._operator_id;
			}
			set
			{
				if ((this._operator_id != value))
				{
					if (this._personal_info_t1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onoperator_idChanging(value);
					this.SendPropertyChanging();
					this._operator_id = value;
					this.SendPropertyChanged("operator_id");
					this.Onoperator_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_administrator_id", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string administrator_id
		{
			get
			{
				return this._administrator_id;
			}
			set
			{
				if ((this._administrator_id != value))
				{
					if (this._personal_info_t.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onadministrator_idChanging(value);
					this.SendPropertyChanging();
					this._administrator_id = value;
					this.SendPropertyChanged("administrator_id");
					this.Onadministrator_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="global_session_t_days_sessions_t", Storage="_days_sessions_ts", ThisKey="daily_id", OtherKey="daily_id")]
		public EntitySet<days_sessions_t> days_sessions_ts
		{
			get
			{
				return this._days_sessions_ts;
			}
			set
			{
				this._days_sessions_ts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="personal_info_t_global_session_t", Storage="_personal_info_t", ThisKey="administrator_id", OtherKey="person_id", IsForeignKey=true)]
		public personal_info_t personal_info_t
		{
			get
			{
				return this._personal_info_t.Entity;
			}
			set
			{
				personal_info_t previousValue = this._personal_info_t.Entity;
				if (((previousValue != value) 
							|| (this._personal_info_t.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._personal_info_t.Entity = null;
						previousValue.global_session_ts.Remove(this);
					}
					this._personal_info_t.Entity = value;
					if ((value != null))
					{
						value.global_session_ts.Add(this);
						this._administrator_id = value.person_id;
					}
					else
					{
						this._administrator_id = default(string);
					}
					this.SendPropertyChanged("personal_info_t");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="personal_info_t_global_session_t1", Storage="_personal_info_t1", ThisKey="operator_id", OtherKey="person_id", IsForeignKey=true)]
		public personal_info_t personal_info_t1
		{
			get
			{
				return this._personal_info_t1.Entity;
			}
			set
			{
				personal_info_t previousValue = this._personal_info_t1.Entity;
				if (((previousValue != value) 
							|| (this._personal_info_t1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._personal_info_t1.Entity = null;
						previousValue.global_session_ts1.Remove(this);
					}
					this._personal_info_t1.Entity = value;
					if ((value != null))
					{
						value.global_session_ts1.Add(this);
						this._operator_id = value.person_id;
					}
					else
					{
						this._operator_id = default(string);
					}
					this.SendPropertyChanged("personal_info_t1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_days_sessions_ts(days_sessions_t entity)
		{
			this.SendPropertyChanging();
			entity.global_session_t = this;
		}
		
		private void detach_days_sessions_ts(days_sessions_t entity)
		{
			this.SendPropertyChanging();
			entity.global_session_t = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.payments_t")]
	public partial class payments_t
	{
		
		private string _client_id;
		
		private double _put_cash;
		
		private System.DateTime _date_of_transaction;
		
		public payments_t()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_id", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string client_id
		{
			get
			{
				return this._client_id;
			}
			set
			{
				if ((this._client_id != value))
				{
					this._client_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_put_cash", DbType="Float NOT NULL")]
		public double put_cash
		{
			get
			{
				return this._put_cash;
			}
			set
			{
				if ((this._put_cash != value))
				{
					this._put_cash = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_transaction", DbType="DateTime NOT NULL")]
		public System.DateTime date_of_transaction
		{
			get
			{
				return this._date_of_transaction;
			}
			set
			{
				if ((this._date_of_transaction != value))
				{
					this._date_of_transaction = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.personal_info_t")]
	public partial class personal_info_t : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _person_id;
		
		private string _name;
		
		private string _staff_login;
		
		private string _staff_password;
		
		private string _position;
		
		private string _phone;
		
		private string _additional_phone;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _home_address;
		
		private int _salary_per_day;
		
		private EntitySet<global_session_t> _global_session_ts;
		
		private EntitySet<global_session_t> _global_session_ts1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onperson_idChanging(string value);
    partial void Onperson_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onstaff_loginChanging(string value);
    partial void Onstaff_loginChanged();
    partial void Onstaff_passwordChanging(string value);
    partial void Onstaff_passwordChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void Onadditional_phoneChanging(string value);
    partial void Onadditional_phoneChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void Onhome_addressChanging(string value);
    partial void Onhome_addressChanged();
    partial void Onsalary_per_dayChanging(int value);
    partial void Onsalary_per_dayChanged();
    #endregion
		
		public personal_info_t()
		{
			this._global_session_ts = new EntitySet<global_session_t>(new Action<global_session_t>(this.attach_global_session_ts), new Action<global_session_t>(this.detach_global_session_ts));
			this._global_session_ts1 = new EntitySet<global_session_t>(new Action<global_session_t>(this.attach_global_session_ts1), new Action<global_session_t>(this.detach_global_session_ts1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_person_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string person_id
		{
			get
			{
				return this._person_id;
			}
			set
			{
				if ((this._person_id != value))
				{
					this.Onperson_idChanging(value);
					this.SendPropertyChanging();
					this._person_id = value;
					this.SendPropertyChanged("person_id");
					this.Onperson_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_login", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string staff_login
		{
			get
			{
				return this._staff_login;
			}
			set
			{
				if ((this._staff_login != value))
				{
					this.Onstaff_loginChanging(value);
					this.SendPropertyChanging();
					this._staff_login = value;
					this.SendPropertyChanged("staff_login");
					this.Onstaff_loginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_password", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string staff_password
		{
			get
			{
				return this._staff_password;
			}
			set
			{
				if ((this._staff_password != value))
				{
					this.Onstaff_passwordChanging(value);
					this.SendPropertyChanging();
					this._staff_password = value;
					this.SendPropertyChanged("staff_password");
					this.Onstaff_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this.OnpositionChanging(value);
					this.SendPropertyChanging();
					this._position = value;
					this.SendPropertyChanged("position");
					this.OnpositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_additional_phone", DbType="VarChar(50)")]
		public string additional_phone
		{
			get
			{
				return this._additional_phone;
			}
			set
			{
				if ((this._additional_phone != value))
				{
					this.Onadditional_phoneChanging(value);
					this.SendPropertyChanging();
					this._additional_phone = value;
					this.SendPropertyChanged("additional_phone");
					this.Onadditional_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string home_address
		{
			get
			{
				return this._home_address;
			}
			set
			{
				if ((this._home_address != value))
				{
					this.Onhome_addressChanging(value);
					this.SendPropertyChanging();
					this._home_address = value;
					this.SendPropertyChanged("home_address");
					this.Onhome_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary_per_day", DbType="Int NOT NULL")]
		public int salary_per_day
		{
			get
			{
				return this._salary_per_day;
			}
			set
			{
				if ((this._salary_per_day != value))
				{
					this.Onsalary_per_dayChanging(value);
					this.SendPropertyChanging();
					this._salary_per_day = value;
					this.SendPropertyChanged("salary_per_day");
					this.Onsalary_per_dayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="personal_info_t_global_session_t", Storage="_global_session_ts", ThisKey="person_id", OtherKey="administrator_id")]
		public EntitySet<global_session_t> global_session_ts
		{
			get
			{
				return this._global_session_ts;
			}
			set
			{
				this._global_session_ts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="personal_info_t_global_session_t1", Storage="_global_session_ts1", ThisKey="person_id", OtherKey="operator_id")]
		public EntitySet<global_session_t> global_session_ts1
		{
			get
			{
				return this._global_session_ts1;
			}
			set
			{
				this._global_session_ts1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_global_session_ts(global_session_t entity)
		{
			this.SendPropertyChanging();
			entity.personal_info_t = this;
		}
		
		private void detach_global_session_ts(global_session_t entity)
		{
			this.SendPropertyChanging();
			entity.personal_info_t = null;
		}
		
		private void attach_global_session_ts1(global_session_t entity)
		{
			this.SendPropertyChanging();
			entity.personal_info_t1 = this;
		}
		
		private void detach_global_session_ts1(global_session_t entity)
		{
			this.SendPropertyChanging();
			entity.personal_info_t1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.playstation_timezone")]
	public partial class playstation_timezone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _playstation_timezone_id;
		
		private string _playstation_id;
		
		private string _timezone_name;
		
		private System.Nullable<double> _timezone_cost_per_hour;
		
		private EntityRef<timezones_t> _timezones_t;
		
		private EntityRef<tables_t> _tables_t;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onplaystation_timezone_idChanging(int value);
    partial void Onplaystation_timezone_idChanged();
    partial void Onplaystation_idChanging(string value);
    partial void Onplaystation_idChanged();
    partial void Ontimezone_nameChanging(string value);
    partial void Ontimezone_nameChanged();
    partial void Ontimezone_cost_per_hourChanging(System.Nullable<double> value);
    partial void Ontimezone_cost_per_hourChanged();
    #endregion
		
		public playstation_timezone()
		{
			this._timezones_t = default(EntityRef<timezones_t>);
			this._tables_t = default(EntityRef<tables_t>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_playstation_timezone_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int playstation_timezone_id
		{
			get
			{
				return this._playstation_timezone_id;
			}
			set
			{
				if ((this._playstation_timezone_id != value))
				{
					this.Onplaystation_timezone_idChanging(value);
					this.SendPropertyChanging();
					this._playstation_timezone_id = value;
					this.SendPropertyChanged("playstation_timezone_id");
					this.Onplaystation_timezone_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_playstation_id", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string playstation_id
		{
			get
			{
				return this._playstation_id;
			}
			set
			{
				if ((this._playstation_id != value))
				{
					if (this._tables_t.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onplaystation_idChanging(value);
					this.SendPropertyChanging();
					this._playstation_id = value;
					this.SendPropertyChanged("playstation_id");
					this.Onplaystation_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timezone_name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string timezone_name
		{
			get
			{
				return this._timezone_name;
			}
			set
			{
				if ((this._timezone_name != value))
				{
					if (this._timezones_t.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontimezone_nameChanging(value);
					this.SendPropertyChanging();
					this._timezone_name = value;
					this.SendPropertyChanged("timezone_name");
					this.Ontimezone_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timezone_cost_per_hour", DbType="Float")]
		public System.Nullable<double> timezone_cost_per_hour
		{
			get
			{
				return this._timezone_cost_per_hour;
			}
			set
			{
				if ((this._timezone_cost_per_hour != value))
				{
					this.Ontimezone_cost_per_hourChanging(value);
					this.SendPropertyChanging();
					this._timezone_cost_per_hour = value;
					this.SendPropertyChanged("timezone_cost_per_hour");
					this.Ontimezone_cost_per_hourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="timezones_t_playstation_timezone", Storage="_timezones_t", ThisKey="timezone_name", OtherKey="timezone_name", IsForeignKey=true)]
		public timezones_t timezones_t
		{
			get
			{
				return this._timezones_t.Entity;
			}
			set
			{
				timezones_t previousValue = this._timezones_t.Entity;
				if (((previousValue != value) 
							|| (this._timezones_t.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._timezones_t.Entity = null;
						previousValue.playstation_timezones.Remove(this);
					}
					this._timezones_t.Entity = value;
					if ((value != null))
					{
						value.playstation_timezones.Add(this);
						this._timezone_name = value.timezone_name;
					}
					else
					{
						this._timezone_name = default(string);
					}
					this.SendPropertyChanged("timezones_t");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tables_t_playstation_timezone", Storage="_tables_t", ThisKey="playstation_id", OtherKey="playstation_id", IsForeignKey=true)]
		public tables_t tables_t
		{
			get
			{
				return this._tables_t.Entity;
			}
			set
			{
				tables_t previousValue = this._tables_t.Entity;
				if (((previousValue != value) 
							|| (this._tables_t.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tables_t.Entity = null;
						previousValue.playstation_timezones.Remove(this);
					}
					this._tables_t.Entity = value;
					if ((value != null))
					{
						value.playstation_timezones.Add(this);
						this._playstation_id = value.playstation_id;
					}
					else
					{
						this._playstation_id = default(string);
					}
					this.SendPropertyChanged("tables_t");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tables_t")]
	public partial class tables_t : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _playstation_id;
		
		private string _playstation_state;
		
		private System.Nullable<System.TimeSpan> _order_time;
		
		private EntitySet<days_sessions_t> _days_sessions_ts;
		
		private EntitySet<playstation_timezone> _playstation_timezones;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onplaystation_idChanging(string value);
    partial void Onplaystation_idChanged();
    partial void Onplaystation_stateChanging(string value);
    partial void Onplaystation_stateChanged();
    partial void Onorder_timeChanging(System.Nullable<System.TimeSpan> value);
    partial void Onorder_timeChanged();
    #endregion
		
		public tables_t()
		{
			this._days_sessions_ts = new EntitySet<days_sessions_t>(new Action<days_sessions_t>(this.attach_days_sessions_ts), new Action<days_sessions_t>(this.detach_days_sessions_ts));
			this._playstation_timezones = new EntitySet<playstation_timezone>(new Action<playstation_timezone>(this.attach_playstation_timezones), new Action<playstation_timezone>(this.detach_playstation_timezones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_playstation_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string playstation_id
		{
			get
			{
				return this._playstation_id;
			}
			set
			{
				if ((this._playstation_id != value))
				{
					this.Onplaystation_idChanging(value);
					this.SendPropertyChanging();
					this._playstation_id = value;
					this.SendPropertyChanged("playstation_id");
					this.Onplaystation_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_playstation_state", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string playstation_state
		{
			get
			{
				return this._playstation_state;
			}
			set
			{
				if ((this._playstation_state != value))
				{
					this.Onplaystation_stateChanging(value);
					this.SendPropertyChanging();
					this._playstation_state = value;
					this.SendPropertyChanged("playstation_state");
					this.Onplaystation_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_time", DbType="Time")]
		public System.Nullable<System.TimeSpan> order_time
		{
			get
			{
				return this._order_time;
			}
			set
			{
				if ((this._order_time != value))
				{
					this.Onorder_timeChanging(value);
					this.SendPropertyChanging();
					this._order_time = value;
					this.SendPropertyChanged("order_time");
					this.Onorder_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tables_t_days_sessions_t", Storage="_days_sessions_ts", ThisKey="playstation_id", OtherKey="playstation_id")]
		public EntitySet<days_sessions_t> days_sessions_ts
		{
			get
			{
				return this._days_sessions_ts;
			}
			set
			{
				this._days_sessions_ts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tables_t_playstation_timezone", Storage="_playstation_timezones", ThisKey="playstation_id", OtherKey="playstation_id")]
		public EntitySet<playstation_timezone> playstation_timezones
		{
			get
			{
				return this._playstation_timezones;
			}
			set
			{
				this._playstation_timezones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_days_sessions_ts(days_sessions_t entity)
		{
			this.SendPropertyChanging();
			entity.tables_t = this;
		}
		
		private void detach_days_sessions_ts(days_sessions_t entity)
		{
			this.SendPropertyChanging();
			entity.tables_t = null;
		}
		
		private void attach_playstation_timezones(playstation_timezone entity)
		{
			this.SendPropertyChanging();
			entity.tables_t = this;
		}
		
		private void detach_playstation_timezones(playstation_timezone entity)
		{
			this.SendPropertyChanging();
			entity.tables_t = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.client_info_t")]
	public partial class client_info_t : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _client_id;
		
		private string _name;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _email;
		
		private string _phone;
		
		private System.DateTime _activation_date;
		
		private System.Nullable<double> _pers_discount;
		
		private double _played_sum;
		
		private EntitySet<days_sessions_t> _days_sessions_ts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onclient_idChanging(string value);
    partial void Onclient_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void Onactivation_dateChanging(System.DateTime value);
    partial void Onactivation_dateChanged();
    partial void Onpers_discountChanging(System.Nullable<double> value);
    partial void Onpers_discountChanged();
    partial void Onplayed_sumChanging(double value);
    partial void Onplayed_sumChanged();
    #endregion
		
		public client_info_t()
		{
			this._days_sessions_ts = new EntitySet<days_sessions_t>(new Action<days_sessions_t>(this.attach_days_sessions_ts), new Action<days_sessions_t>(this.detach_days_sessions_ts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string client_id
		{
			get
			{
				return this._client_id;
			}
			set
			{
				if ((this._client_id != value))
				{
					this.Onclient_idChanging(value);
					this.SendPropertyChanging();
					this._client_id = value;
					this.SendPropertyChanged("client_id");
					this.Onclient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activation_date", DbType="Date NOT NULL")]
		public System.DateTime activation_date
		{
			get
			{
				return this._activation_date;
			}
			set
			{
				if ((this._activation_date != value))
				{
					this.Onactivation_dateChanging(value);
					this.SendPropertyChanging();
					this._activation_date = value;
					this.SendPropertyChanged("activation_date");
					this.Onactivation_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pers_discount", DbType="Float")]
		public System.Nullable<double> pers_discount
		{
			get
			{
				return this._pers_discount;
			}
			set
			{
				if ((this._pers_discount != value))
				{
					this.Onpers_discountChanging(value);
					this.SendPropertyChanging();
					this._pers_discount = value;
					this.SendPropertyChanged("pers_discount");
					this.Onpers_discountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_played_sum", DbType="Float NOT NULL")]
		public double played_sum
		{
			get
			{
				return this._played_sum;
			}
			set
			{
				if ((this._played_sum != value))
				{
					this.Onplayed_sumChanging(value);
					this.SendPropertyChanging();
					this._played_sum = value;
					this.SendPropertyChanged("played_sum");
					this.Onplayed_sumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="client_info_t_days_sessions_t", Storage="_days_sessions_ts", ThisKey="client_id", OtherKey="client_id")]
		public EntitySet<days_sessions_t> days_sessions_ts
		{
			get
			{
				return this._days_sessions_ts;
			}
			set
			{
				this._days_sessions_ts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_days_sessions_ts(days_sessions_t entity)
		{
			this.SendPropertyChanging();
			entity.client_info_t = this;
		}
		
		private void detach_days_sessions_ts(days_sessions_t entity)
		{
			this.SendPropertyChanging();
			entity.client_info_t = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.session_accounting_t")]
	public partial class session_accounting_t
	{
		
		private System.Nullable<int> _session_id;
		
		private double _payed_sum;
		
		private double _played_money;
		
		private string _comments;
		
		private System.Nullable<double> _session_discount;
		
		public session_accounting_t()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_session_id", DbType="Int")]
		public System.Nullable<int> session_id
		{
			get
			{
				return this._session_id;
			}
			set
			{
				if ((this._session_id != value))
				{
					this._session_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payed_sum", DbType="Float NOT NULL")]
		public double payed_sum
		{
			get
			{
				return this._payed_sum;
			}
			set
			{
				if ((this._payed_sum != value))
				{
					this._payed_sum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_played_money", DbType="Float NOT NULL")]
		public double played_money
		{
			get
			{
				return this._played_money;
			}
			set
			{
				if ((this._played_money != value))
				{
					this._played_money = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="VarChar(100)")]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this._comments = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_session_discount", DbType="Float")]
		public System.Nullable<double> session_discount
		{
			get
			{
				return this._session_discount;
			}
			set
			{
				if ((this._session_discount != value))
				{
					this._session_discount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
